import React, { createContext, useContext, useState, useEffect } from "react";

const SettingsContext = createContext();

//  Full Dictionary for Complete Translation across all pages
const translations = {
  en: {
    // ---------------- SETTINGS PAGE ----------------
    appSettings: "App Settings",
    settingsSub: "Manage your interface appearance, audio fidelity, playback behaviors, and explore upcoming features.",
    accountOverview: "Account Overview",
    interfaceApp: "Interface & Appearance",
    audioPlay: "Audio & Playback",
    dataPrivacy: "Data & Privacy",
    upcomingFeatures: "Upcoming Features Roadmap",
    guestUser: "Guest User",
    adminRole: "Administrator",
    freeTier: "Free Tier",
    glowThemeAccent: "Glow Theme Accent",
    themeDesc: "Select your primary ambient lighting and glowing gradient highlight color.",
    glassBlur: "Glass Backdrop Blur",
    glassDesc: "Adjust the frost intensity of glass cards and background panels live.",
    compactSidebar: "Compact Navigation Sidebar",
    compactSidebarDesc: "Collapse navigation text labels to maximize dashboard workspace.",
    explicitTags: "Explicit Content Tags",
    explicitTagsDesc: "Display explicit content indicator badges on songs and album listings.",
    displayLang: "Display Language",
    langDesc: "Choose the primary language for the application interface.",
    audioQualityTitle: "Streaming Audio Quality",
    audioQualityDesc: "Higher bitrates offer superior clarity but consume more bandwidth.",
    eqPresetTitle: "Equalizer Audio Preset",
    eqPresetDesc: "Adjust frequency curves for your specific headphones or speakers.",
    crossfadeTitle: "Crossfade Songs",
    crossfadeDesc: "Seamlessly blend transitions between consecutive audio tracks.",
    spatialAudio: "Spatial Audio / Dolby Atmos",
    spatialAudioDesc: "Enable immersive 3D surround sound for supported tracks.",
    autoPlay: "Auto-Play Similar Tracks",
    autoPlayDesc: "Keep the music going endlessly when your playlist finishes.",
    normalizeVol: "Normalize Volume",
    normalizeVolDesc: "Set the same volume level for all tracks automatically.",
    dataSaver: "Data Saver Mode",
    dataSaverDesc: "Disable background videos and force low audio quality on mobile networks.",
    privateSession: "Private Listening Session",
    privateSessionDesc: "Hide your listening history temporarily from profile statistics.",
    shareActivity: "Share Listening Activity",
    shareActivityDesc: "Allow friends to view live updates of tracks you are playing.",
    nextUpdates: "Next Updates",
    roadmapDesc: "Get an early preview of upcoming modules! Toggle 'Notify Me' to get instant alerts when these features launch.",
    comingSoon: "Coming Soon",
    betaPreview: "Beta Preview",
    aiDj: "AI Smart DJ Transition",
    aiDjDesc: "Generative AI transitions that blend bpm, keys, and vocal acapellas seamlessly between songs.",
    eqTuner: "10-Band Graphic EQ Tuner",
    eqTunerDesc: "Precise manual decibel controls across 10 frequency bands for advanced audiophiles.",
    cloudSync: "Cross-Device Sync & Backup",
    cloudSyncDesc: "Instant cloud backup for offline downloads, equalizer profiles, and layout settings.",
    visualizer: "Real-time 3D Canvas Visualizer",
    visualizerDesc: "Audio-reactive GPU shader visualizers with customizable particle waves and beat-sync glow.",
    normalQuality: "Normal (96 kbps - Saver)",
    highQuality: "High (160 kbps - Standard)",
    veryHighQuality: "Very High (320 kbps - HQ)",
    losslessQuality: "Lossless Audio (FLAC - Hi-Fi)",
    eqFlat: "Flat (Default)",
    eqBass: "Bass Boost",
    eqElectronic: "Electronic / EDM",
    eqVocal: "Vocal Boost",
    eqAcoustic: "Acoustic / Live",
    saveChanges: "Save Changes",
    saved: "Saved!",
    resetDefaults: "Reset Defaults",
    notifyMe: "Notify Me",
    subscribed: "Subscribed!",
    toastSaved: "All preferences saved successfully! ✨",
    toastReset: "Settings reset to defaults. Remember to save!",
    toastLang: "Language updated to",
    toastTheme: "Theme switched to",
    toastSubscribed: "early access notifications! 🚀",
    toastUnsubscribed: "Unsubscribed from updates.",

    // ---------------- SIDEBAR & NAVIGATION ----------------
    home: "Home",
    search: "Search",
    library: "Your Library",
    topSongs: "Top Songs",
    createPlaylist: "Create Playlist",
    likedSongs: "Liked Songs",
    adminDashboard: "Admin Dashboard",
    settings: "Settings",
    yourPlaylists: "YOUR PLAYLISTS",
    searchPlaceholder: "Search songs, artists, or albums...",
    topSignUp: "Sign up",
    topLogIn: "Log In",
    goBackTitle: "Go back",
    goForwardTitle: "Go forward",
    accountLabel: "Account",
    logoutLabel: "Log out",
    logoutSuccessToast: "Logged out successfully",

    // ---------------- HOME PAGE ----------------
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    goodNight: "Good Night",
    exploreUniverse: "Explore your custom audio universe today.",
    selectVibe: "Select a vibe to ignite audio",
    recentlyPlayed: "Recently Played",
    liveBadge: "LIVE",
    discoverVibez: "Discover Vibez",
    filterTrending: "Trending",
    filterTamil: "Tamil",
    filterEnglish: "English",
    filterMalayalam: "Malayalam",
    filterHindi: "Hindi",
    filterTelugu: "Telugu",

    // --- VIBEIFY AESTHETIC TEXT ---
    featuredTrack: "spotlight vibez",
    listenNow: "Play Vibez",
    trendingVibeToday: "Trending #1 Vibe",
    vibeVerseStream: "VIBE-VERSE STREAM",
    trendzHits: "TRENDZ HITS",
    queueVibez: "Queue Vibez",
    tracks: "tracks", // 👈 Added tracks translation

    // ---------------- TOP SONGS PAGE ----------------
    streamVibezz: "STREAM VIBEZZ SONGS",
    vibeifyTop: "Vibeify Top Vibezz",
    discoverTop: "Discover the most streamed tracks, trending hits, and viral anthems across the ecosystem.",
    topVibezz: "Top Vibezz",
    trendingVibezz: "Trending Vibezz",
    viralVibezz: "Viral Vibezz",
    filterVibezz: "Filter Vibezz...",
    title: "TITLE",
    album: "ALBUM",
    actions: "ACTIONS",
    artist: "ARTIST",
    fetchingVibezz: "Fetching Cyber Vibezz...",
    noVibezzFound: "No Vibezz Found",
    adjustSearch: "Try adjusting your search query or switching chart tabs.",
    loginToSaveFav: "Please log in to save your favorite songs!",
    failedToLoadTop: "Failed to load Top Vibezz",
    linkCopied: "Link copied to clipboard! 🔗",
    failedToCopy: "Failed to copy link",
    pausedTrack: "Paused",
    resumedTrack: "Resumed",
    nowPlayingTrack: "Now Playing:",

    // ---------------- SEARCH PAGE & OVERLAY ----------------
    all: "All",
    songsTab: "Songs",
    artists: "Artists",
    albums: "Albums",
    topResult: "Top Result",
    songLabel: "SONG",
    noAlbumsMatched: "No albums matched your search.",
    noSongsMatched: "No songs matched your search.",
    noArtistsMatched: "No artists matched your search.",
    searchVibeify: "Search Vibeify",
    searchSubtitle: "Find your favorite songs, artists, and albums in seconds.",
    noResultsFor: "No results found for",
    checkSpelling: "Please check your spelling or search with a different keyword.",
    failedFetchSearch: "Failed to fetch search catalogue!",
    playingTrack: "Playing",
    searchOverlayPlaceholder: "Search songs, artists, or albums...",
    trendingSearchesHeader: "Trending Searches",
    resultsForHeader: "Results for",
    viewAllLink: "View All ➔",
    playTag: "Play ▶",
    noLocalTracksMatch: "No local tracks matching",
    searchGlobalDb: "Search full global database ➔",
    searchingFor: "Searching for",

    // ---------------- LIBRARY & PLAYLISTS ----------------
    manageEcosystem: "Manage your personal audio ecosystem",
    playlists: "Playlists",
    song: "song",
    songs: "songs",
    publicPlaylist: "PUBLIC PLAYLIST",
    privatePlaylist: "PRIVATE PLAYLIST",
    vibeifyOfficial: "Vibeify Official",
    emptyPlaylist: "This playlist is empty. Click the (+) button above to add songs.",
    playingFromAlbum: "PLAYING FROM ALBUM",
    deletePlaylistConfirm: "Delete playlist",
    deletedPlaylistToast: "deleted 🗑️",
    failedDeletePlaylist: "Failed to delete playlist. Please try again!",
    playlistEmptyToast: "is empty!",
    playingPlaylistToast: "Playing",
    loadingCollection: "Loading your collection...",
    noPlaylistsYet: "No Playlists Yet",
    createFirstPlaylist: "Create your first custom playlist and start building your ultimate vibe collection.",
    exploreSongsToAdd: "Explore Songs to Add",
    playPlaylistTitle: "Play Playlist",
    deletePlaylistTitle: "Delete Playlist",
    noLikedSongsYet: "No Liked Songs Yet",
    tapHeartToSave: "Tap the heart icon on any song to save it to your collection.",
    exploreSongs: "Explore Songs",
    
    // ---------------- MODALS & SEARCH ----------------
    createPlaylistModal: "CREATE PLAYLIST",
    newCyberPlaylist: "New Cyber Playlist",
    configPlaylist: "Configure track vibes and privacy controls",
    myCyberPlaylist: "My Cyber Playlist",
    playlistName: "PLAYLIST NAME",
    playlistPlaceholder: "e.g. Synthwave Night Drive",
    privacyVisibility: "PRIVACY VISIBILITY",
    public: "Public",
    private: "Private",
    cancel: "Cancel",
    trendingSearches: "TRENDING SEARCHES",
    close: "Close",
    vibesLabel: "VIBES",
    newPlaylistModalTitle: "New Playlist",
    synthesizeSubtitle: "Synthesize a brand new track collection",
    untitledPlaylist: "Untitled Playlist",
    titleLabel: "Title",
    enterTitlePlaceholder: "Enter title (e.g. Cyberpunk Nights)",
    privacySettingLabel: "Privacy Setting",
    playlistCreatedToast: "created!",

    // ---------------- ADMIN DASHBOARD ----------------
    overview: "Overview",
    totalSongs: "Total Songs",
    totalUsers: "Total Users",
    totalPlaylists: "Total Playlists",
    admins: "Admins",
    users: "Users",
    songUploads: "Song Uploads (Last 7 Days)",
    recentlyAddedSongs: "Recently Added Songs",
    newestUsers: "Newest Users",
    songTitleForm: "Song Title *",
    artistNameForm: "Artist Name *",
    albumOptionalForm: "Album (Optional)",
    selectCategoryForm: "SELECT CATEGORY / VIBE *",
    audioTrackForm: "AUDIO TRACK (MP3/WAV) *",
    chooseAudio: "Choose audio track...",
    coverArtworkForm: "COVER ARTWORK (PNG/JPG) *",
    chooseCover: "Choose cover image...",
    publishSong: "Publish Song",
    existingCatalog: "Existing Catalog",
    searchCatalog: "Search title, artist or category...",
    registeredUsers: "Registered Users",
    searchUsers: "Search username or email...",
    userRole: "user",
    adminRoleLabel: "admin",
    userHeader: "USER",
    emailHeader: "EMAIL",
    accessLevelHeader: "ACCESS LEVEL",
    adminAccessDenied: "Access Denied: Admin permissions required!",
    switchedToAdmin: "Switched to Admin",
    adminRequiredMsg: "You need an admin account to view this dashboard. Set a user's role to 'admin' directly in MongoDB to unlock access.",
    systemMetricsUpdated: "System metrics updated",
    failedFetchMetrics: "Failed to fetch system metrics from server",
    loadingMetrics: "Loading dashboard metrics...",
    failedLoadMetrics: "Failed to load system metrics. Please refresh.",
    noSongsUploaded: "No songs uploaded yet.",
    noUsersRegistered: "No users registered yet.",
    uploadingTrack: "Uploading Track...",
    failedFetchSongsCatalog: "Failed to fetch songs catalog",
    audioAttached: "Audio track attached:",
    coverAttached: "Cover artwork attached:",
    completeRequiredFields: "Please complete all required fields and select both valid files.",
    publishingToCloud: "Publishing song to cloud infrastructure...",
    publishedSuccessfully: "successfully published!",
    uploadFailed: "Upload failed. Check server connection.",
    confirmDeleteTrack: "Are you sure you want to permanently delete",
    deletedTrack: "Deleted track",
    couldNotDeleteSong: "Could not delete song",
    noMatchingSongs: "No matching songs found in database.",
    failedFetchUsers: "Failed to fetch user accounts",
    updatedAccessLevel: "access level updated to",
    failedModifyRole: "Failed to modify user role",
    confirmDeleteUser: "Delete user and all associated playlists permanently?",
    userAccountDeleted: "User account deleted",
    failedRemoveUser: "Failed to remove user account",
    fetchingUsers: "Fetching users...",
    youTag: "(you)",
    noUserAccountsFound: "No user accounts found.",

    // ---------------- PROFILE PAGE ----------------
    proMember: "PRO MEMBER",
    editProfile: "Edit Profile",
    songsPlayed: "Songs Played",
    playlistsCreated: "Playlists Created",
    listeningTime: "Listening Time",
    accountInfo: "Account Information",
    quickSettings: "Quick Settings",
    usernameLabel: "USERNAME",
    emailLabel: "EMAIL ADDRESS",
    accountRoleLabel: "ACCOUNT ROLE",
    statusLabel: "STATUS",
    statusActive: "Active",
    notifications: "Notifications",
    privacySecurity: "Privacy & Security",
    signOut: "Sign Out",
    profileLoginPrompt: "Please log in to view your profile dashboard!",
    profileLoadError: "Failed to load profile statistics!",
    featureComingSoon: "clicked! Feature coming soon.",
    accessDenied: "Access Denied",
    accessDeniedDesc: "Please log in to view your profile dashboard and personal stats.",
    defaultUserRole: "User",

    // ---------------- AUTH & GUEST PAGES ----------------
    welcomeBack: "Welcome Back",
    loginJumpBack: "Log in to jump back into your vibes",
    emailAddress: "EMAIL ADDRESS",
    password: "PASSWORD",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    logIn: "Log In",
    dontHaveAccount: "Don't have an account?",
    signUpVibeify: "Sign up for Vibeify",
    createAccount: "Create Account",
    signUpListen: "Sign up to start listening to your favorite vibes",
    username: "USERNAME",
    whatToCallYou: "What should we call you?",
    signUp: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Log in here",
    loginViewPlaylists: "Log in to view your playlists",
    guestExplorerMode: "GUEST EXPLORER MODE",
    unlockUniverse: "Unlock the Full Vibeify Universe",
    signupPromo: "Sign up now to build custom playlists, save liked tracks, and enjoy unlimited lossless audio...",
    signupFree: "Sign up for free",
    libraryEmpty: "Your Library is Empty",
    libraryGuestPromo: "Log in to view your saved playlists, liked tracks, and personalized collections.",
    logInVibeify: "Log In to Vibeify",

    // ---------------- NOW PLAYING PAGE ----------------
    addedToLikedSongs: "Added to Liked Songs ❤️",
    removedFromLikedSongs: "Removed from Liked Songs",
    shuffleEnabled: "Shuffle enabled 🔀",
    shuffleDisabled: "Shuffle disabled",
    repeatEnabled: "Repeat enabled 🔁",
    repeatDisabled: "Repeat disabled",
    addedTo: "Added to",
    failedToAddTrack: "Failed to add track",
    audioMuted: "Audio muted 🔇",
    vibeifyStudioRelease: "Vibeify Studio Release",
    addToPlaylistHeader: "ADD TO PLAYLIST",
    noPlaylistsFound: "No playlists found",
    artistSpotlight: "Artist Spotlight",
    verifiedArtistBlurb: "Verified artist. Stream all top hits and discover new releases curated on Vibeify.",
    trackCredits: "Track Credits",
    songTitleLabel: "Song Title",
    mainArtistLabel: "Main Artist",
    albumReleaseLabel: "Album / Release",
    singleRelease: "Single",
    totalDurationLabel: "Total Duration",
    upNextInQueue: "Up Next in Queue",
    
    // ---------------- PLAYLIST DETAILS PAGE ----------------
    loadingPlaylist: "Loading playlist...",
    failedLoadPlaylist: "Failed to load playlist details!",
    addedTrackPrefix: "Added",
    toPlaylistSuffix: "to playlist! 🎵",
    failedAddSong: "Failed to add song to playlist!",
    removedTrackPrefix: "Removed",
    fromPlaylistSuffix: "from playlist! 🗑️",
    failedRemoveSong: "Failed to remove song from playlist!",
    playingPlaylistPrefix: "Playing playlist",
    shufflePlayingPrefix: "Shuffle playing",
    publicPlaylistType: "Public Playlist",
    vibeifyOfficialLabel: "Vibeify Official",
    songsCountLabel: "songs",
    playBtn: "Play",
    pauseBtn: "Pause",
    shufflePlayBtn: "Shuffle Play",
    addSongsBtn: "Add Songs",
    addTracksHeader: "Add tracks to playlist",
    doneBtn: "Done",
    addedBtn: "Added",
    thTitle: "Title",
    thArtist: "Artist",
    emptyPlaylistMsg: "This playlist is empty. Click the (+) button above to add songs.",
    removeFromPlaylist: "Remove from playlist",

    // ---------------- ALBUMS PAGE & ALBUM DETAILS ----------------
    noAlbumsYet: "No albums yet.",
    songsWillGroup: "Songs will group into albums here once uploaded.",
    loadingAlbum: "Loading album...",
    backBtn: "Back",
    albumNotFound: "Album not found.",
    albumLabel: "Album",
    playAlbumBtn: "Play Album",

    // ---------------- LAYOUT PAGE & COMPONENTS ----------------
    sidebarClosed: "Sidebar closed",
    vibeifyAudioApp: "Vibeify Audio Application",
    closeNotification: "Close notification",
    
    // ---------------- SONG CARD ----------------
    trackArtAlt: "Track art",
    pauseSongAria: "Pause song",
    playSongAria: "Play song",

    // ---------------- PLAYER COMPONENT ----------------
    selectVibePrompt: "Select a vibe to ignite audio",
    likeSongTitle: "Like song",
    shuffleTooltip: "Shuffle",
    prevSongTooltip: "Previous",
    playTooltip: "Play",
    pauseTooltip: "Pause",
    nextSongTooltip: "Next",
    repeatTooltip: "Repeat",
    muteTooltip: "Mute / Unmute",
    expandPlayerTooltip: "Expand Player",
    expandPlayerAria: "Expand player view",
    playPauseAria: "Play or Pause",
    previousTrackAria: "Previous track",
    nextTrackAria: "Next track",
    toggleMuteAria: "Toggle mute"
  },

  ta: {
    // ---------------- SETTINGS PAGE ----------------
    appSettings: "பயன்பாட்டு அமைப்புகள்",
    settingsSub: "உங்கள் இடைமுகத் தோற்றம், ஆடியோ தரம், பிளேபேக் நடத்தைகள் மற்றும் வரவிருக்கும் அம்சங்களை நிர்வகிக்கவும்.",
    accountOverview: "கணக்கு மேலோட்டம்",
    interfaceApp: "இடைமுகம் மற்றும் தோற்றம்",
    audioPlay: "ஆடியோ மற்றும் பிளேபேக்",
    dataPrivacy: "தரவு மற்றும் தனியுரிமை",
    upcomingFeatures: "வரவிருக்கும் அம்சங்கள்",
    guestUser: "விருந்தினர்",
    adminRole: "நிர்வாகி",
    freeTier: "இலவச நிலை",
    glowThemeAccent: "பளபளப்பான தீம் (Glow Theme)",
    themeDesc: "உங்கள் முதன்மை ஒளியமைப்பு மற்றும் வண்ணத்தை தேர்ந்தெடுக்கவும்.",
    glassBlur: "கண்ணாடி மங்கலாகும் அளவு (Glass Blur)",
    glassDesc: "பின்னணி பேனல்களின் உறைபனி தீவிரத்தை சரிசெய்யவும்.",
    compactSidebar: "சுருக்கமான வழிசெலுத்தல் பக்கப்பட்டி",
    compactSidebarDesc: "பலகை இடத்தினை அதிகரிக்க வழிசெலுத்தல் உரை லேபிள்களைச் சுருக்கவும்.",
    explicitTags: "வெளிப்படையான உள்ளடக்க குறிச்சொற்கள்",
    explicitTagsDesc: "பாடல்கள் மற்றும் ஆல்பம் பட்டியல்களில் வெளிப்படையான உள்ளடக்க குறிப்பான்களைக் காட்டுக.",
    displayLang: "காட்சி மொழி",
    langDesc: "பயன்பாட்டு இடைமுகத்திற்கான முதன்மை மொழியைத் தேர்ந்தெடுக்கவும்.",
    audioQualityTitle: "ஸ்ட்ரீமிங் ஆடியோ தரம்",
    audioQualityDesc: "அதிக பிட்ரேட்கள் சிறந்த தெளிவை வழங்குகின்றன, ஆனால் அதிக டேட்டாவை பயன்படுத்துகின்றன.",
    eqPresetTitle: "ஈக்வலைசர் ஆடியோ முன்னமைவு",
    eqPresetDesc: "உங்கள் ஹெட்ஃபோன்கள் அல்லது ஸ்பீக்கர்களுக்கான அதிர்வெண் வளைவுகளை சரிசெய்யவும்.",
    crossfadeTitle: "பாடல்களை இணைக்கவும் (Crossfade)",
    crossfadeDesc: "தொடர்ச்சியான ஆடியோ டிராக்குகளுக்கு இடையே தடையின்றி மாற்றங்களை கலக்கவும்.",
    spatialAudio: "இடவெளி ஆடியோ / டால்பி அட்மாஸ்",
    spatialAudioDesc: "ஆதரிக்கப்படும் பாடல்களுக்கு ஆழமான 3D ஒலியை இயக்குக.",
    autoPlay: "ஒத்த பாடல்களைத் தானாக இயக்கு",
    autoPlayDesc: "உங்கள் பிளேலிஸ்ட் முடிந்தவுடன் இசையைத் தொடர்ந்து ஒலிக்கச் செய்யவும்.",
    normalizeVol: "ஒலியளவை சீராக்கு",
    normalizeVolDesc: "அனைத்து பாடல்களுக்கும் ஒரே ஒலியளவை தானாகவே அமைக்கவும்.",
    dataSaver: "டேட்டா சேமிப்பு முறை",
    dataSaverDesc: "மொபைல் நெட்வொர்க்குகளில் பின்னணி வீடியோக்களை முடக்கி, குறைந்த ஆடியோ தரத்தை கட்டாயமாக்கு.",
    privateSession: "தனிப்பட்ட கேட்கும் அமர்வு",
    privateSessionDesc: "உங்கள் சுயவிவரப் புள்ளிவிவரங்களிலிருந்து உங்கள் கேட்கும் வரலாற்றை தற்காலிகமாக மறைக்கவும்.",
    shareActivity: "கேட்கும் செயல்பாட்டைப் பகிரவும்",
    shareActivityDesc: "நீங்கள் கேட்கும் பாடல்களின் நேரடி புதுப்பிப்புகளைப் பார்க்க நண்பர்களை அனுமதிக்கவும்.",
    nextUpdates: "அடுத்த புதுப்பிப்புகள்",
    roadmapDesc: "வரவிருக்கும் தொகுதிகளின் ஆரம்ப மாதிரிக்காட்சியைப் பெறுங்கள்! இந்த அம்சங்கள் தொடங்கும் போது உடனடி அறிவிப்புகளைப் பெற 'எனக்குத் தெரியப்படுத்து' என்பதை மாற்றவும்.",
    comingSoon: "விரைவில்",
    betaPreview: "பீட்டா மாதிரிக்காட்சி",
    aiDj: "AI ஸ்மார்ட் DJ மாற்றம்",
    aiDjDesc: "பாடல்களுக்கு இடையில் bpm, விசைகள் மற்றும் குரல் அகாபெல்லாக்களை தடையின்றி கலக்கும் ஜெனரேட்டிவ் AI மாற்றங்கள்.",
    eqTuner: "10-பேண்ட் கிராஃபிக் ஈக்யூ ட்யூனர்",
    eqTunerDesc: "மேம்பட்ட ஆடியோஃபில்களுக்கான 10 அதிர்வெண் பேண்டுகளில் துல்லியமான கையேடு டெசிபல் கட்டுப்பாடுகள்.",
    cloudSync: "குறுக்கு-சாதன ஒத்திசைவு மற்றும் காப்புப்பிரதி",
    cloudSyncDesc: "ஆஃப்லைன் பதிவிறக்கங்கள், ஈக்வலைசர் சுயவிவரங்கள் மற்றும் தளவமைப்பு அமைப்புகளுக்கான உடனடி கிளவுட் காப்புப்பிரதி.",
    visualizer: "நிகழ்நேர 3D கேன்வாஸ் விசுவலைசர்",
    visualizerDesc: "தனிப்பயனாக்கக்கூடிய துகள் அலைகள் மற்றும் பீட்-சின்க் பளபளப்பு கொண்ட ஆடியோ-எதிர்வினை GPU ஷேடர் விசுவலைசர்கள்.",
    normalQuality: "சாதாரண (96 kbps - சேமிப்பான்)",
    highQuality: "உயர் (160 kbps - தரநிலை)",
    veryHighQuality: "மிக உயர்ந்த (320 kbps - HQ)",
    losslessQuality: "இழப்பற்ற ஆடியோ (FLAC - Hi-Fi)",
    eqFlat: "தட்டையான (இயல்புநிலை)",
    eqBass: "பாஸ் பூஸ்ட்",
    eqElectronic: "எலக்ட்ரானிக் / EDM",
    eqVocal: "குரல் பூஸ்ட்",
    eqAcoustic: "அகௌஸ்டிக் / நேரடி",
    saveChanges: "மாற்றங்களைச் சேமி",
    saved: "சேமிக்கப்பட்டது!",
    resetDefaults: "இயல்புநிலைக்கு மீட்டமை",
    notifyMe: "எனக்குத் தெரியப்படுத்து",
    subscribed: "சந்தா செய்யப்பட்டது!",
    toastSaved: "அனைத்து விருப்பங்களும் வெற்றிகரமாக சேமிக்கப்பட்டன! ✨",
    toastReset: "அமைப்புகள் இயல்புநிலைக்கு மீட்டமைக்கப்பட்டன. சேமிக்க மறக்காதீர்கள்!",
    toastLang: "மொழி புதுப்பிக்கப்பட்டது:",
    toastTheme: "தீம் மாற்றப்பட்டது:",
    toastSubscribed: "ஆரம்ப அணுகல் அறிவிப்புகளுக்கு சந்தா செய்யப்பட்டது! 🚀",
    toastUnsubscribed: "புதுப்பிப்புகளிலிருந்து குழுவிலகினீர்கள்.",

    // ---------------- SIDEBAR & NAVIGATION ----------------
    home: "முகப்பு",
    search: "தேடல்",
    library: "உங்கள் நூலகம்",
    topSongs: "சிறந்த பாடல்கள்",
    createPlaylist: "பிளேலிஸ்ட்டை உருவாக்கு",
    likedSongs: "விருப்பமான பாடல்கள்",
    adminDashboard: "நிர்வாகக் குழு",
    settings: "அமைப்புகள்",
    yourPlaylists: "உங்கள் பிளேலிஸ்ட்கள்",
    searchPlaceholder: "பாடல்கள், கலைஞர்கள் அல்லது ஆல்பங்களைத் தேடுக...",
    topSignUp: "பதிவு செய்",
    topLogIn: "உள்நுழை",
    goBackTitle: "பின்செல்",
    goForwardTitle: "முன்செல்",
    accountLabel: "கணக்கு",
    logoutLabel: "வெளியேறு",
    logoutSuccessToast: "வெற்றிகரமாக வெளியேறினீர்கள்",

    // ---------------- HOME PAGE ----------------
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    goodNight: "இரவு வணக்கம்",
    exploreUniverse: "இன்று உங்கள் தனிப்பயன் ஆடியோ பிரபஞ்சத்தை ஆராயுங்கள்.",
    selectVibe: "ஆடியோவைத் தொடங்க ஒரு வைப்பைத் தேர்ந்தெடுக்கவும்",
    recentlyPlayed: "சமீபத்தில் கேட்டவை",
    liveBadge: "நேரலை",
    discoverVibez: "வைப்ஸைக் கண்டறியுங்கள்",
    filterTrending: "டிரெண்டிங்",
    filterTamil: "தமிழ்",
    filterEnglish: "ஆங்கிலம்",
    filterMalayalam: "மலையாளம்",
    filterHindi: "இந்தி",
    filterTelugu: "தெலுங்கு",

    // --- VIBEIFY AESTHETIC TEXT ---
    featuredTrack: "ஸ்பாட்லைட் வைப்ஸ்",
    listenNow: "வைப்ஸை இயக்கு",
    trendingVibeToday: "ட்ரெண்டிங் #1 வைப்",
    vibeVerseStream: "வைப்-வெர்ஸ் ஸ்ட்ரீம்",
    trendzHits: "ட்ரெண்ட்ஸ் ஹிட்ஸ்",
    queueVibez: "க்யூ வைப்ஸ்",
    tracks: "பாடல்கள்", //  Added tracks translation (Tamil)

    // ---------------- TOP SONGS PAGE ----------------
    streamVibezz: "வைப்ஸ் பாடல்களை ஸ்ட்ரீம் செய்",
    vibeifyTop: "வைபிஃபை டாப் வைப்ஸ்",
    discoverTop: "அதிகமாக ஸ்ட்ரீம் செய்யப்பட்ட டிராக்குகள், டிரெண்டிங் ஹிட்ஸ் மற்றும் வைரல் பாடல்களை கண்டறியவும்.",
    topVibezz: "சிறந்த வைப்ஸ்",
    trendingVibezz: "டிரெண்டிங் வைப்ஸ்",
    viralVibezz: "வைரல் வைப்ஸ்",
    filterVibezz: "வைப்ஸை வடிகட்டு...",
    title: "தலைப்பு",
    album: "ஆல்பம்",
    actions: "செயல்கள்",
    artist: "கலைஞர்",
    fetchingVibezz: "சைபர் வைப்ஸைப் பெறுகிறது...",
    noVibezzFound: "வைப்ஸ்கள் எதுவும் கிடைக்கவில்லை",
    adjustSearch: "உங்கள் தேடலை மாற்ற முயற்சிக்கவும் அல்லது சார்ட் தாவல்களை மாற்றவும்.",
    loginToSaveFav: "உங்களுக்குப் பிடித்த பாடல்களைச் சேமிக்க உள்நுழையவும்!",
    failedToLoadTop: "சிறந்த வைப்ஸை ஏற்றுவதில் தோல்வி",
    linkCopied: "இணைப்பு கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது! 🔗",
    failedToCopy: "இணைப்பை நகலெடுப்பதில் தோல்வி",
    pausedTrack: "இடைநிறுத்தப்பட்டது",
    resumedTrack: "தொடரப்பட்டது",
    nowPlayingTrack: "இப்போது ஒலிக்கிறது:",

    // ---------------- SEARCH PAGE & OVERLAY ----------------
    all: "அனைத்தும்",
    songsTab: "பாடல்கள்",
    artists: "கலைஞர்கள்",
    albums: "ஆல்பங்கள்",
    topResult: "சிறந்த முடிவு",
    songLabel: "பாடல்",
    noAlbumsMatched: "உங்கள் தேடலுக்குப் பொருந்தக்கூடிய ஆல்பங்கள் எதுவும் இல்லை.",
    noSongsMatched: "உங்கள் தேடலுக்குப் பொருந்தக்கூடிய பாடல்கள் எதுவும் இல்லை.",
    noArtistsMatched: "உங்கள் தேடலுக்குப் பொருந்தக்கூடிய கலைஞர்கள் யாரும் இல்லை.",
    searchVibeify: "வைபிஃபையில் தேடுக",
    searchSubtitle: "உங்களுக்குப் பிடித்த பாடல்கள், கலைஞர்கள் மற்றும் ஆல்பங்களை நொடிகளில் கண்டறியுங்கள்.",
    noResultsFor: "இதற்கான முடிவுகள் எதுவும் இல்லை:",
    checkSpelling: "உங்கள் எழுத்துக்களை சரிபார்க்கவும் அல்லது வேறு வார்த்தையுடன் தேடவும்.",
    failedFetchSearch: "தேடல் பட்டியலைப் பெறுவதில் தோல்வி!",
    playingTrack: "ஒலிக்கிறது",
    searchOverlayPlaceholder: "பாடல்கள், கலைஞர்கள் அல்லது ஆல்பங்களைத் தேடுக...",
    trendingSearchesHeader: "டிரெண்டிங் தேடல்கள்",
    resultsForHeader: "முடிவுகள்",
    viewAllLink: "அனைத்தையும் காண்க ➔",
    playTag: "இயக்கு ▶",
    noLocalTracksMatch: "இதனுடன் பொருந்தக்கூடிய உள்நாட்டுப் பாடல்கள் இல்லை",
    searchGlobalDb: "முழு உலகளாவிய தரவுத்தளத்தைத் தேடுக ➔",
    searchingFor: "தேடுகிறது",

    // ---------------- LIBRARY & PLAYLISTS ----------------
    manageEcosystem: "உங்கள் தனிப்பட்ட ஆடியோ சூழல் அமைப்பை நிர்வகிக்கவும்",
    playlists: "பிளேலிஸ்ட்கள்",
    song: "பாடல்",
    songs: "பாடல்கள்",
    publicPlaylist: "பொது பிளேலிஸ்ட்",
    privatePlaylist: "தனிப்பட்ட பிளேலிஸ்ட்",
    vibeifyOfficial: "வைபிஃபை அதிகாரப்பூர்வ",
    emptyPlaylist: "இந்த பிளேலிஸ்ட் காலியாக உள்ளது. பாடல்களைச் சேர்க்க, மேலே உள்ள (+) பொத்தானைக் கிளிக் செய்யவும்.",
    playingFromAlbum: "ஆல்பத்திலிருந்து ஒலிக்கிறது",
    deletePlaylistConfirm: "பிளேலிஸ்ட்டை நீக்கவா:",
    deletedPlaylistToast: "நீக்கப்பட்டது 🗑️",
    failedDeletePlaylist: "பிளேலிஸ்ட்டை நீக்குவதில் தோல்வி. மீண்டும் முயற்சிக்கவும்!",
    playlistEmptyToast: "காலியாக உள்ளது!",
    playingPlaylistToast: "ஒலிக்கிறது",
    loadingCollection: "உங்கள் தொகுப்பை ஏற்றுகிறது...",
    noPlaylistsYet: "பிளேலிஸ்ட்கள் எதுவும் இல்லை",
    createFirstPlaylist: "உங்கள் முதல் தனிப்பயன் பிளேலிஸ்ட்டை உருவாக்கி, உங்கள் விருப்பமான பாடல்களைச் சேர்க்கத் தொடங்குங்கள்.",
    exploreSongsToAdd: "சேர்க்க பாடல்களை ஆராயுங்கள்",
    playPlaylistTitle: "பிளேலிஸ்ட்டை இயக்கு",
    deletePlaylistTitle: "பிளேலிஸ்ட்டை நீக்கு",
    noLikedSongsYet: "விருப்பமான பாடல்கள் எதுவும் இல்லை",
    tapHeartToSave: "உங்கள் தொகுப்பில் சேமிக்க எந்தப் பாடலிலும் உள்ள இதய ஐகானைத் தட்டவும்.",
    exploreSongs: "பாடல்களை ஆராயுங்கள்",
    
    // ---------------- MODALS & SEARCH ----------------
    createPlaylistModal: "பிளேலிஸ்ட்டை உருவாக்கு",
    newCyberPlaylist: "புதிய சைபர் பிளேலிஸ்ட்",
    configPlaylist: "ட்ராக் வைப்ஸ் மற்றும் தனியுரிமை கட்டுப்பாடுகளை உள்ளமைக்கவும்",
    myCyberPlaylist: "என் சைபர் பிளேலிஸ்ட்",
    playlistName: "பிளேலிஸ்ட் பெயர்",
    playlistPlaceholder: "உதாரணம்: இரவு பயணப் பாடல்கள்",
    privacyVisibility: "தனியுரிமைத் தன்மை",
    public: "பொது",
    private: "தனிப்பட்ட",
    cancel: "ரத்துசெய்",
    trendingSearches: "டிரெண்டிங் தேடல்கள்",
    close: "மூடு",
    vibesLabel: "வைப்ஸ்",
    newPlaylistModalTitle: "புதிய பிளேலிஸ்ட்",
    synthesizeSubtitle: "புதிய பாடல் தொகுப்பை உருவாக்கவும்",
    untitledPlaylist: "தலைப்பில்லாத பிளேலிஸ்ட்",
    titleLabel: "தலைப்பு",
    enterTitlePlaceholder: "தலைப்பை உள்ளிடவும் (உதா. சைபர்பಂಕ್ இரவுகள்)",
    privacySettingLabel: "தனியுரிமை அமைப்பு",
    playlistCreatedToast: "உருவாக்கப்பட்டது!",

    // ---------------- ADMIN DASHBOARD ----------------
    overview: "மேலோட்டம்",
    totalSongs: "மொத்த பாடல்கள்",
    totalUsers: "மொத்த பயனர்கள்",
    totalPlaylists: "மொத்த பிளேலிஸ்ட்கள்",
    admins: "நிர்வாகிகள்",
    users: "பயனர்கள்",
    songUploads: "பாடல் பதிவேற்றங்கள் (கடந்த 7 நாட்கள்)",
    recentlyAddedSongs: "சமீபத்தில் சேர்க்கப்பட்ட பாடல்கள்",
    newestUsers: "புதிய பயனர்கள்",
    songTitleForm: "பாடல் தலைப்பு *",
    artistNameForm: "கலைஞர் பெயர் *",
    albumOptionalForm: "ஆல்பம் (விருப்பத்திற்குரியது)",
    selectCategoryForm: "வகை / வைப்பைத் தேர்ந்தெடுக்கவும் *",
    audioTrackForm: "ஆடியோ டிராக் (MP3/WAV) *",
    chooseAudio: "ஆடியோ ட்ராக்கைத் தேர்ந்தெடுக்கவும்...",
    coverArtworkForm: "அட்டைப்படம் (PNG/JPG) *",
    chooseCover: "அட்டைப்படத்தைத் தேர்ந்தெடுக்கவும்...",
    publishSong: "பாடலை வெளியிடு",
    existingCatalog: "தற்போதுள்ள பட்டியல்",
    searchCatalog: "தலைப்பு, கலைஞர் அல்லது வகையைத் தேடுக...",
    registeredUsers: "பதிவு செய்யப்பட்ட பயனர்கள்",
    searchUsers: "பயனர் பெயர் அல்லது மின்னஞ்சலைத் தேடுக...",
    userRole: "பயனர்",
    adminRoleLabel: "நிர்வாகி",
    userHeader: "பயனர்",
    emailHeader: "மின்னஞ்சல்",
    accessLevelHeader: "அணுகல் நிலை",
    adminAccessDenied: "அனுமதி மறுக்கப்பட்டது: நிர்வாகி அனுமதிகள் தேவை!",
    switchedToAdmin: "நிர்வாகி தாவலுக்கு மாற்றப்பட்டது:",
    adminRequiredMsg: "இந்த டேஷ்போர்டைப் பார்க்க உங்களுக்கு நிர்வாகி கணக்கு தேவை. அணுகலைத் திறக்க MongoDB-ல் பயனரின் பங்கை 'admin' என அமைக்கவும்.",
    systemMetricsUpdated: "கணினி அளவீடுகள் புதுப்பிக்கப்பட்டன",
    failedFetchMetrics: "கணினி அளவீடுகளைப் பெறுவதில் தோல்வி",
    loadingMetrics: "டேஷ்போர்டு அளவீடுகளை ஏற்றுகிறது...",
    failedLoadMetrics: "கணினி அளவீடுகளை ஏற்றுவதில் தோல்வி. பக்கத்தை புதுப்பிக்கவும்.",
    noSongsUploaded: "பாடல்கள் எதுவும் பதிவேற்றப்படவில்லை.",
    noUsersRegistered: "பயனர்கள் யாரும் பதிவு செய்யவில்லை.",
    uploadingTrack: "பாடல் பதிவேற்றப்படுகிறது...",
    failedFetchSongsCatalog: "பாடல்கள் பட்டியலைப் பெறுவதில் தோல்வி",
    audioAttached: "ஆடியோ டிராக் இணைக்கப்பட்டது:",
    coverAttached: "அட்டைப்படம் இணைக்கப்பட்டது:",
    completeRequiredFields: "அனைத்து கட்டாய புலங்களையும் நிரப்பி, சரியான கோப்புகளைத் தேர்ந்தெடுக்கவும்.",
    publishingToCloud: "பாடலை கிளவுட் சேவையகத்தில் வெளியிடுகிறது...",
    publishedSuccessfully: "வெற்றிகரமாக வெளியிடப்பட்டது!",
    uploadFailed: "பதிவேற்றம் தோல்வியடைந்தது. சேவையக இணைப்பைச் சரிபார்க்கவும்.",
    confirmDeleteTrack: "இந்த பாடலை நிரந்தரமாக நீக்க விரும்புகிறீர்களா?",
    deletedTrack: "நிரந்தரமாக நீக்கப்பட்டது 🗑️",
    couldNotDeleteSong: "பாடலை நீக்க முடியவில்லை",
    noMatchingSongs: "தரவுத்தளத்தில் பொருந்தக்கூடிய பாடல்கள் எதுவும் இல்லை.",
    failedFetchUsers: "பயனர் கணக்குகளைப் பெறுவதில் தோல்வி",
    updatedAccessLevel: "அணுகல் நிலை புதுப்பிக்கப்பட்டது 🛡️",
    failedModifyRole: "பயனர் பங்கை மாற்றுவதில் தோல்வி",
    confirmDeleteUser: "இந்த பயனரையும் அவரது பிளேலிஸ்ட்களையும் நிரந்தரமாக நீக்க விரும்புகிறீர்களா?",
    userAccountDeleted: "பயனர் கணக்கு நீக்கப்பட்டது 🗑️",
    failedRemoveUser: "பயனர் கணக்கை அகற்றுவதில் தோல்வி",
    fetchingUsers: "பயனர்களைப் பெறுகிறது...",
    youTag: "(நீங்கள்)",
    noUserAccountsFound: "பயனர் கணக்குகள் எதுவும் இல்லை.",

    // ---------------- PROFILE PAGE ----------------
    proMember: "ப்ரோ உறுப்பினர்",
    editProfile: "சுயவிவரத்தைத் திருத்து",
    songsPlayed: "கேட்ட பாடல்கள்",
    playlistsCreated: "உருவாக்கிய பிளேலிஸ்ட்கள்",
    listeningTime: "கேட்ட நேரம்",
    accountInfo: "கணக்கு தகவல்",
    quickSettings: "விரைவு அமைப்புகள்",
    usernameLabel: "பயனர் பெயர்",
    emailLabel: "மின்னஞ்சல் முகவரி",
    accountRoleLabel: "கணக்கு பங்கு",
    statusLabel: "நிலை",
    statusActive: "செயலில்",
    notifications: "அறிவிப்புகள்",
    privacySecurity: "தனியுரிமை மற்றும் பாதுகாப்பு",
    signOut: "வெளியேறு",
    profileLoginPrompt: "உங்கள் சுயவிவரப் பார்க்க உள்நுழையவும்!",
    profileLoadError: "சுயவிவர புள்ளிவிவரங்களை ஏற்றுவதில் தோல்வி!",
    featureComingSoon: "கிளிக் செய்யப்பட்டது! அம்சம் விரைவில் வரும்.",
    accessDenied: "அனுமதி மறுக்கப்பட்டது",
    accessDeniedDesc: "உங்கள் சுயவிவரப் பார்க்கவும் புள்ளிவிவரங்களை அறியவும் உள்நுழையவும்.",
    defaultUserRole: "பயனர்",

    // ---------------- AUTH & GUEST PAGES ----------------
    welcomeBack: "மீண்டும் வருக",
    loginJumpBack: "உங்கள் வைப்ஸை மீண்டும் கேட்க உள்நுழையவும்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    rememberMe: "என்னை நினைவில் கொள்க",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    logIn: "உள்நுழை",
    dontHaveAccount: "கணக்கு இல்லையா?",
    signUpVibeify: "வைபிஃபை-ல் பதிவு செய்யவும்",
    createAccount: "கணக்கை உருவாக்கு",
    signUpListen: "உங்களுக்குப் பிடித்த வைப்ஸைக் கேட்க பதிவு செய்யவும்",
    username: "பயனர் பெயர்",
    whatToCallYou: "உங்களை எப்படி அழைக்க வேண்டும்?",
    signUp: "பதிவு செய்",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    loginHere: "இங்கே உள்நுழையவும்",
    loginViewPlaylists: "உங்கள் பிளேலிஸ்ட்களைப் பார்க்க உள்நுழையவும்",
    guestExplorerMode: "விருந்தினர் எக்ஸ்ப்ளோரர் பயன்முறை",
    unlockUniverse: "முழு வைபிஃபை பிரபஞ்சத்தையும் திறக்கவும்",
    signupPromo: "தனிப்பயன் பிளேலிஸ்ட்களை உருவாக்க, விருப்பமான பாடல்களைச் சேமிக்க மற்றும் வரம்பற்ற இழப்பற்ற ஆடியோவை ரசிக்க இப்போதே பதிவு செய்யவும்...",
    signupFree: "இலவசமாக பதிவு செய்யவும்",
    libraryEmpty: "உங்கள் நூலகம் காலியாக உள்ளது",
    libraryGuestPromo: "உங்கள் சேமிக்கப்பட்ட பிளேலிஸ்ட்கள், விருப்பமான பாடல்கள் மற்றும் தனிப்பயனாக்கப்பட்ட தொகுப்புகளைப் பார்க்க உள்நுழையவும்.",
    logInVibeify: "வைபிஃபை-ல் உள்நுழையவும்",

    // ---------------- NOW PLAYING PAGE ----------------
    addedToLikedSongs: "விருப்பமான பாடல்களில் சேர்க்கப்பட்டது ❤️",
    removedFromLikedSongs: "விருப்பமான பாடல்களிலிருந்து அகற்றப்பட்டது",
    shuffleEnabled: "கலைத்து இயக்குதல் இயக்கப்பட்டது 🔀",
    shuffleDisabled: "கலைத்து இயக்குதல் முடக்கப்பட்டது",
    repeatEnabled: "மீண்டும் இயக்குதல் இயக்கப்பட்டது 🔁",
    repeatDisabled: "மீண்டும் இயக்குதல் முடக்கப்பட்டது",
    addedTo: "இதில் சேர்க்கப்பட்டது",
    failedToAddTrack: "பாடலைச் சேர்ப்பதில் தோல்வி",
    audioMuted: "ஆடியோ முடக்கப்பட்டது 🔇",
    vibeifyStudioRelease: "வைபிஃபை ஸ்டுடியோ வெளியீடு",
    addToPlaylistHeader: "பிளேலிஸ்ட்டில் சேர்",
    noPlaylistsFound: "பிளேலிஸ்ட்கள் எதுவும் இல்லை",
    artistSpotlight: "கலைஞர் சிறப்பம்சம்",
    verifiedArtistBlurb: "சரிபார்க்கப்பட்ட கலைஞர். வைபிஃபையில் தேர்ந்தெடுக்கப்பட்ட சிறந்த ஹிட்களையும் புதிய வெளியீடுகளையும் கேளுங்கள்.",
    trackCredits: "பாடல் விவரங்கள்",
    songTitleLabel: "பாடல் தலைப்பு",
    mainArtistLabel: "முக்கிய கலைஞர்",
    albumReleaseLabel: "ஆல்பம் / வெளியீடு",
    singleRelease: "சிங்கிள் (Single)",
    totalDurationLabel: "மொத்த நேரம்",
    upNextInQueue: "வரிசையில் அடுத்து",

    // ---------------- PLAYLIST DETAILS PAGE ----------------
    loadingPlaylist: "பிளேலிஸ்ட் ஏற்றப்படுகிறது...",
    failedLoadPlaylist: "பிளேலிஸ்ட் விவரங்களை ஏற்றுவதில் தோல்வி!",
    addedTrackPrefix: "பிளேலிஸ்ட்டில்",
    toPlaylistSuffix: "சேர்க்கப்பட்டது! 🎵",
    failedAddSong: "பிளேலிஸ்ட்டில் பாடலைச் சேர்ப்பதில் தோல்வி!",
    removedTrackPrefix: "பிளேலிஸ்ட்டிலிருந்து",
    fromPlaylistSuffix: "அகற்றப்பட்டது! 🗑️",
    failedRemoveSong: "பிளேலிஸ்ட்டிலிருந்து பாடலை அகற்றுவதில் தோல்வி!",
    playingPlaylistPrefix: "பிளேலிஸ்ட் ஒலிக்கிறது:",
    shufflePlayingPrefix: "கலைத்து ஒலிக்கிறது:",
    publicPlaylistType: "பொது பிளேலிஸ்ட்",
    vibeifyOfficialLabel: "வைபிஃபை அதிகாரப்பூர்வ",
    songsCountLabel: "பாடல்கள்",
    playBtn: "இயக்கு",
    pauseBtn: "இடைநிறுத்து",
    shufflePlayBtn: "கலைத்து இயக்கு",
    addSongsBtn: "பாடல்களைச் சேர்",
    addTracksHeader: "பிளேலிஸ்ட்டில் பாடல்களைச் சேர்",
    doneBtn: "முடிந்தது",
    addedBtn: "சேர்க்கப்பட்டது",
    thTitle: "தலைப்பு",
    thArtist: "கலைஞர்",
    emptyPlaylistMsg: "இந்த பிளேலிஸ்ட் காலியாக உள்ளது. பாடல்களைச் சேர்க்க, மேலே உள்ள (+) பொத்தானைக் கிளிக் செய்யவும்.",
    removeFromPlaylist: "பிளேலிஸ்ட்டிலிருந்து அகற்று",

    // ---------------- ALBUMS PAGE & ALBUM DETAILS ----------------
    noAlbumsYet: "இன்னும் ஆல்பங்கள் இல்லை.",
    songsWillGroup: "பதிவேற்றியவுடன் பாடல்கள் இங்கே ஆல்பங்களாக தொகுக்கப்படும்.",
    loadingAlbum: "ஆல்பம் ஏற்றப்படுகிறது...",
    backBtn: "பின்செல்",
    albumNotFound: "ஆல்பம் காணப்படவில்லை.",
    albumLabel: "ஆல்பம்",
    playAlbumBtn: "ஆல்பத்தை இயக்கு",

    // ---------------- LAYOUT PAGE & COMPONENTS ----------------
    sidebarClosed: "பக்கப்பட்டி மூடப்பட்டது",
    vibeifyAudioApp: "வைபிஃபை ஆடியோ பயன்பாடு",
    closeNotification: "அறிவிப்பை மூடு",
    
    // ---------------- SONG CARD ----------------
    trackArtAlt: "பாடல் அட்டைப்படம்",
    pauseSongAria: "பாடலை இடைநிறுத்து",
    playSongAria: "பாடலை இயக்கு",

    // ---------------- PLAYER COMPONENT ----------------
    selectVibePrompt: "ஆடியோவைத் தொடங்க ஒரு வைப்பைத் தேர்ந்தெடுக்கவும்",
    likeSongTitle: "பாடலை விரும்பு",
    shuffleTooltip: "கலைத்து இயக்கு",
    prevSongTooltip: "முந்தையது",
    playTooltip: "இயக்கு",
    pauseTooltip: "இடைநிறுத்து",
    nextSongTooltip: "அடுத்து",
    repeatTooltip: "மீண்டும் இயக்கு",
    muteTooltip: "ஒலியடக்கு / ஒலியூட்டு",
    expandPlayerTooltip: "ப்ளேயரை விரிவாக்கு",
    expandPlayerAria: "ப்ளேயர் காட்சியை விரிவாக்கு",
    playPauseAria: "இயக்கு அல்லது இடைநிறுத்து",
    previousTrackAria: "முந்தைய பாடல்",
    nextTrackAria: "அடுத்த பாடல்",
    toggleMuteAria: "ஒலியடக்குதலை மாற்று"
  }
};

export const SettingsProvider = ({ children }) => {
  const loadBool = (key, defaultVal) => {
    const saved = localStorage.getItem(key);
    return saved !== null ? JSON.parse(saved) : defaultVal;
  };

  const [language, setLanguage] = useState(() => localStorage.getItem("vibeify_language") || "en");
  const [theme, setTheme] = useState(() => localStorage.getItem("vibeify_theme") || "violet");
  const [glassIntensity, setGlassIntensity] = useState(() => Number(localStorage.getItem("vibeify_glass_blur")) || 24);

  const [compactSidebar, setCompactSidebar] = useState(() => loadBool("vibeify_compact_sidebar", false));
  const [explicitBadges, setExplicitBadges] = useState(() => loadBool("vibeify_explicit_badges", true));

  const [audioQuality, setAudioQuality] = useState(() => localStorage.getItem("vibeify_audio_quality") || "high");
  const [eqPreset, setEqPreset] = useState(() => localStorage.getItem("vibeify_eq_preset") || "flat");
  const [crossfade, setCrossfade] = useState(() => Number(localStorage.getItem("vibeify_crossfade")) || 3);
  const [normalizeVolume, setNormalizeVolume] = useState(() => loadBool("vibeify_normalize", true));
  const [spatialAudio, setSpatialAudio] = useState(() => loadBool("vibeify_spatial_audio", false));
  const [autoPlay, setAutoPlay] = useState(() => loadBool("vibeify_autoplay", true));

  const [dataSaver, setDataSaver] = useState(() => loadBool("vibeify_data_saver", false));
  const [privateSession, setPrivateSession] = useState(() => loadBool("vibeify_private_session", false));
  const [showActivity, setShowActivity] = useState(() => loadBool("vibeify_share_activity", true));

  useEffect(() => {
    localStorage.setItem("vibeify_language", language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    localStorage.setItem("vibeify_theme", theme);
    localStorage.setItem("vibeify_glass_blur", glassIntensity.toString());

    const root = document.documentElement;
    root.style.setProperty("--glass-blur", `${glassIntensity}px`);

    const themeAccents = {
      violet: { primary: "#8b5cf6", secondary: "#ff4ecd", glow: "rgba(255, 78, 205, 0.35)" },
      pink: { primary: "#ec4899", secondary: "#f43f5e", glow: "rgba(244, 63, 94, 0.35)" },
      emerald: { primary: "#10b981", secondary: "#06b6d4", glow: "rgba(6, 182, 212, 0.35)" },
      gold: { primary: "#f59e0b", secondary: "#ef4444", glow: "rgba(239, 68, 68, 0.35)" },
    };
    
    const activeTheme = themeAccents[theme] || themeAccents.violet;
    root.style.setProperty("--accent-primary", activeTheme.primary);
    root.style.setProperty("--accent-secondary", activeTheme.secondary);
    root.style.setProperty("--accent-glow", activeTheme.glow);
    root.style.setProperty("--accent-gradient", `linear-gradient(135deg, ${activeTheme.primary}, ${activeTheme.secondary})`);
    
    document.body.className = `theme-${theme}`;
  }, [theme, glassIntensity]);

  useEffect(() => {
    localStorage.setItem("vibeify_compact_sidebar", JSON.stringify(compactSidebar));
    localStorage.setItem("vibeify_explicit_badges", JSON.stringify(explicitBadges));
    localStorage.setItem("vibeify_audio_quality", audioQuality);
    localStorage.setItem("vibeify_eq_preset", eqPreset);
    localStorage.setItem("vibeify_crossfade", crossfade.toString());
    localStorage.setItem("vibeify_normalize", JSON.stringify(normalizeVolume));
    localStorage.setItem("vibeify_spatial_audio", JSON.stringify(spatialAudio));
    localStorage.setItem("vibeify_autoplay", JSON.stringify(autoPlay));
    localStorage.setItem("vibeify_data_saver", JSON.stringify(dataSaver));
    localStorage.setItem("vibeify_private_session", JSON.stringify(privateSession));
    localStorage.setItem("vibeify_share_activity", JSON.stringify(showActivity));

    if (compactSidebar) {
      document.body.classList.add("compact-sidebar-enabled");
    } else {
      document.body.classList.remove("compact-sidebar-enabled");
    }

  }, [
    compactSidebar, explicitBadges, audioQuality, eqPreset, crossfade, 
    normalizeVolume, spatialAudio, autoPlay, dataSaver, privateSession, showActivity
  ]);

  const t = (key) => {
    return translations[language]?.[key] || translations["en"][key] || key;
  };

  return (
    <SettingsContext.Provider value={{ 
      language, setLanguage, 
      theme, setTheme, 
      glassIntensity, setGlassIntensity, 
      compactSidebar, setCompactSidebar,
      explicitBadges, setExplicitBadges,
      audioQuality, setAudioQuality,
      eqPreset, setEqPreset,
      crossfade, setCrossfade,
      normalizeVolume, setNormalizeVolume,
      spatialAudio, setSpatialAudio,
      autoPlay, setAutoPlay,
      dataSaver, setDataSaver,
      privateSession, setPrivateSession,
      showActivity, setShowActivity,
      t 
    }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => useContext(SettingsContext);